### ISSUE TITLE
SS2OM - missing object when estimating steepness 

### ISSUE THREAD

**Issue by AdrianHordyk** [tcarruth/MSEtool#17]
I'm getting the following error with `SS2OM`: `Error in SRopt(nsim, SSB, rec, SpR0, plot = FALSE, type = SR) : object 'SR' not found ` 

In my case `replist$SRRtype` = 7, so it looks like `SR` isn't been defined in the if-else statement. Should it default to "BH"?

**Comment by quang-huynh** [comment]
In this case, SR is now defined to be Beverton-Holt by default.

`SRRtype = 7` is a 3-parameter stock-recruit function which could accommodated in the future: 
https://github.com/DLMtool/DLMtool/issues/48

For now, a Beverton-Holt function is used with the same steepness as the 3-parameter function as an approximation.
