### ISSUE TITLE
SS2OM failing for DLMDev Vermillion Snapper

### ISSUE THREAD

**Issue by AdrianHordyk** [tcarruth/MSEtool#27]
Error in ts(x) : 'ts' object must have one or more observations 
Traceback:
7. stop("'ts' object must have one or more observations") 
6. ts(x) 
5. as.ts.default(x) 
4. as.ts(x) 
3. na.action(as.ts(x)) 
2. acf(dev_for_AC[dev_for_AC != 0], plot = FALSE) at SS2OM.R#404
1. SS2OM("data/SS", nsim = nsim)

**Comment by AdrianHordyk** [comment]
Also Yellowfin_Tuna_IOTC and Yellowfin_Tuna2_IOTC. Different issue:
Error in (function (dir = "C:/myfiles/mymodels/myrun/", dir.mcmc = NULL,  : 
  all columns are used and some data may been missed,
  increase 'ncols' input above current value (ncols=200) 
7. stop("r4ss::SS_output function returned an error -\n", replist, 
    call. = FALSE) at SS2OM.R#67
6. SS2OM("data/io_h80_q1_tm30_dw1") at Build.r#4
5. eval(ei, envir) 
4. eval(ei, envir) 
3. withVisible(eval(ei, envir)) 
2. source("Build.r") at makeCaseStudyTable.R#64
1. makeTable(OMdf)

**Comment by quang-huynh** [comment]
@AdrianHordyk the YFT issue is in r4ss::SS_output. Can you re-run with SS2OM(ncols = 1e3)?

**Comment by AdrianHordyk** [comment]
Fixed
