### ISSUE TITLE
Couple more SS2Data issues

### ISSUE THREAD

**Issue by tcarruth** [tcarruth/MSEtool#32]
Data@AddInd is also a three dimensional array
Data@CV_Ind must have same dimensions as Data@Ind

**Comment by quang-huynh** [comment]
This commit will fix the dimensions of AddInd https://github.com/DLMtool/DLMtool/commit/119d76ff1980bda205b19b2d8ddb599cfbf1099b

In the meantime, SS2Data will create 3-dimensional matrix if empty. Data@Ind and Data@CV_Ind are no longer used in SS2Data in favor of Addind
